# -*- coding: utf-8 -*-
"""InterpretadorZero.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UPkEbYH8d5-0HGoWrLPNsG4Z2RJpSuM4
"""

pip install --upgrade openai

from openai import OpenAI
client  = OpenAI(api_key = "COLOCA A CHAVE AQUI")
assistant_id = "asst_Ue4igFcEmKz45YCFbyiJkzqd"

file = client.files.create(
    file = open("ecg_teste.jpg","rb"),
    purpose = "assistants"

)

print(file)

thread = client.beta.threads.create()
print(thread)

message = client.beta.threads.messages.create(
    thread_id = thread.id,
    role = "user",
    content = [
        {
            "type": "image_file",
            "image_file":
            {
                "file_id": file.id
            }
        },
        {
            "type": "text",
            "text": "Voce pode interpretar esse exame ECG para mim?"
        }
    ]
)

run = client.beta.threads.runs.create(
    thread_id = thread.id,
    assistant_id = assistant_id
)

messages = client.beta.threads.messages.list(
    thread_id = thread.id
)

for message in reversed(messages.data):
    # Check if the content block has a text field
    if message.content[0].type == "text":
        # Print the text if it exists
        print(message.role + ": " + message.content[0].text.value)
    # Check if the content is an image
    elif message.content[0].type == "image_file":
        print(message.role + ": (Image message)")  # Indicate an image message
    else:
        print(message.role + ": (Other content type)") # Handle other message content types as needed